### ISSUE TITLE
When applying subtitle style to UIMenu the TextJustification.Center glitches

### ISSUE THREAD

**Issue by pjotr07740** [alexguirre/RAGENativeUI#106]
![image](https://user-images.githubusercontent.com/65234760/98159889-9fa61700-1edd-11eb-9884-ae3b2bdaf93e.png)

My code:
![image](https://user-images.githubusercontent.com/65234760/98160036-e3008580-1edd-11eb-9523-ed3bb730cd1c.png)

**Comment by alexguirre** [comment]
I'm afraid that's the expected result. `TextJustification.Center` centers the text around its drawing position, which is the left side of the menu.

**Comment by pjotr07740** [comment]
> I'm afraid that's the expected result. `TextJustification.Center` centers the text around its drawing position, which is the left side of the menu.

Oh, okay. I'll have to use the default then. Thanks for your reply!
