### ISSUE TITLE
Menu's seem to be stretched in ultrwawide 3440x1440 resolution

### ISSUE THREAD

**Issue by a101gl** [alexguirre/RAGENativeUI#115]
Hello,

Recently I tried out the 1.7.0 version of RageNativeUI for Scene Manger (https://www.lcpdfr.com/downloads/gta5mods/scripts/27954-scene-manager/) and menus no longer seem to fit with my 3440x1440 resolution anymore, compared to when I was using 1.6.3.  I was looking at a previous issue (https://github.com/alexguirre/RAGENativeUI/issues/98) that seemed to be already fixed, but somehow the bug is occurring for me when using 1.7.0.

**Comment by alexguirre** [comment]
Hi, it should be fixed but a new version with the fix wasn't released yet. Can you try this build?
[RAGENativeUI.zip](https://github.com/alexguirre/RAGENativeUI/files/5992296/RAGENativeUI.zip)

If it still doesn't work, please, provide some screenshots.

**Comment by a101gl** [comment]
This worked, thank you!

**Comment by a101gl** [comment]
This works! Thank you!
