### ISSUE TITLE
Issue with UltraWide Display

### ISSUE THREAD

**Issue by justintdavis99** [alexguirre/RAGENativeUI#116]
I am having an issue with running NativeUI plugins on my ultrawide monitor using the latest UI update.  The UI is scaled too large and does not fit on my screen.  The UI runs off of the left hand side.  I'm running a 2560x1080 monitor with the same resolution ingame.  Any thoughts?

**Comment by justintdavis99** [comment]
Plugins so far that it effects are Stop The Ped, Immersive Dispatch, and CompuLite.  All plugins that I haven't had an issue with before.

**Comment by alexguirre** [comment]
Can you try this build? https://github.com/alexguirre/RAGENativeUI/issues/115#issuecomment-780193935

**Comment by justintdavis99** [comment]
Thanks! This is definitely an improvement.  It completely fixes the display issues with it, but when using CompuLite and using the mouse to navigate around in it, I have to offset my mouse about half an inch to the left of whatever item I am trying to select and click there.  The selection regions seem off.  Using keyboard to navigate seems to be fine though.  Sorry if that doesn't make sense.  Struggling to put that in technical terms.

**Comment by alexguirre** [comment]
The mouse controls are implemented by CompuLite not RAGENativeUI, so sadly I cannot do much. Probably some visual change from the new version that CompuLite is not taking into account.

**Comment by justintdavis99** [comment]
Gotcha, makes sense! I appreciate your time and help on this!!! Really appreciate you getting that issue taken care of and back to where I can use it again! Thank you!
