### ISSUE TITLE
Fix for ultrawide menus not released

### ISSUE THREAD

**Issue by VixenKasai** [alexguirre/RAGENativeUI#123]
The BejoIjo plugins server continues to get people with ultrawide monitors who have issues.
These issues have been fixed in #104 and merged, but have not been built into a full release.

When can we expect a new release containing these patches?

**Comment by alexguirre** [comment]
[1.8](https://github.com/alexguirre/RAGENativeUI/releases/tag/1.8) has been released and it contains those patches.
