### ISSUE TITLE
BadgeStyle

### ISSUE THREAD

**Issue by GravityScriptsV2** [alexguirre/RAGENativeUI#150]
Hello, where can I find a list of BadgeStyles? Also how does Custom Badges Work? Would be great if you had documentation on it. Please lmk ASAP. Thanks

**Comment by alexguirre** [comment]
In Visual Studio, if you type `UIMenu.BadgeStyle.` Intellisense should show a list with all styles. You can check the source code too, they are defined here: https://github.com/alexguirre/RAGENativeUI/blob/master/Source/Elements/MenuItems/UIMenuItem.cs#L442-L474
If you mean a list where you can see how each badge looks, there isn't one currently but the badge textures are defined below, here: https://github.com/alexguirre/RAGENativeUI/blob/master/Source/Elements/MenuItems/UIMenuItem.cs#L639-L666
Just use CodeWalker or OpenIV and search for `commonmenu.ytd`, open it and look for the texture names.

For custom badges, you use the class `UIMenuItem.BadgeInfo` and the properties `UIMenuItem.LeftBadgeInfo` and `UIMenuItem.RightBadgeInfo`.
The `BadgeInfo` constructor is:
```csharp
public BadgeInfo(string textureDictionary, string textureName,
                 Color? color,
                 string selectedTextureDictionary = null, string selectedTextureName = null,
                 float sizeMultiplier = 1.0f)
```
So you can use it like this:
```csharp
myItem.RightBadgeInfo = new UIMenuItem.BadgeInfo("commonmenu", "mp_alerttriangle", Color.Red);
```
`selectedTextureDictionary` and `selectedTextureName` are optional and are used to show an alternative texture when the item with the badge is selected. `sizeMultiplier` may need to be tweaked to fit the badge in the item, depending on the texture size.

**Comment by GravityScriptsV2** [comment]
Thank you!

**Comment by GravityScriptsV2** [comment]
is there a way to use custom Badges?

**Comment by GravityScriptsV2** [comment]
like imported from a file

**Comment by alexguirre** [comment]
No, the badges require a texture dictionary (a .ytd file) as it uses game natives to draw them. You can create a .ytd with your custom textures and install it in the mods folder or with LML.

There is some work in progress for the next RNUI version to allow creating texture dictionaries at runtime so you can load external texture files, but it will still be a while until it releases.

**Comment by GravityScriptsV2** [comment]
Thank you!
