### ISSUE TITLE
Need help registering ItemSelect

### ISSUE THREAD

**Issue by gard971** [alexguirre/RAGENativeUI#158]
I cannot figure out why my menu will not register when a button is pressed, I get the menu to show up fine but then it seems pressing the menu buttons ingame has no effect?

`        public static void menuInit()
        {
            Game.DisplayNotification("Main Menu Toggle");
            mainMenu = new UIMenu("medical menu", "test");
            var adren = new UIMenuItem("Administer Adrenaline and start CPR");
            var CPR = new UIMenuItem("Start CPR");
            adren.Activated += (menu, item) =>
            {
                Game.DisplayNotification("", "", "The patient survived", "", "You selected " + adren.Text);
            };
            CPR.Activated += (menu, item) =>
            {
                Game.DisplayNotification("", "", "The patient did not survive", "", "You selected " + CPR.Text);
            };
            mainMenu.AddItems(adren, CPR);
            myMenuPool.Add(mainMenu);
            GameFiber.StartNew(ProccessMenus);
        }`

I see in the example the void is private. Would this cause an issue? 
Also the menu is part of a LSPDFR callout, in a separate class, then the menu is activated by the callout. Could this cause any issues?

**Comment by gard971** [comment]
![image](https://user-images.githubusercontent.com/32454699/216908945-73e0e033-4cc9-4c51-8ca8-f82658637f59.png)

**Comment by alexguirre** [comment]
That code looks ok. Can you try adding `Game.LogTrivial("some text")` to your `Activated` event handlers and see if it appears in the log after pressing the menu buttons? Using that `Game.DisplayNotification` overload without the icon texture may not be valid.

**Comment by gard971** [comment]
I will try when I get home, it might be as simple as that now that you mention it. In the other notifications, I have left it with one parameter and the notification appeared so hopefully that is it

**Comment by gard971** [comment]
well, that's slightly embarrassing. That fixed it. I guess il blame it on being new to c# or something haha
thank you for the help
