### ISSUE TITLE
License breach

### ISSUE THREAD

**Issue by Michael21107** [alexguirre/RAGENativeUI#165]
is there a way to report license breaches of RNUI (eg. including RNUI without the license) and should we?

**Comment by Variapolis** [comment]
You should make sure you contact the author in breach of the license first incase it is a mistake.

**Comment by Michael21107** [comment]
It's Bejoijo...

**Comment by alexguirre** [comment]
Yeah, you really only can contact the author about it. It's not like I have resources to enforce the license. You won't get far with Bejoijo though...

**Comment by Michael21107** [comment]
yea
