### ISSUE TITLE
LiveLights crash when opening dialogue box - b1.9.3.0

### ISSUE THREAD

**Issue by Walkf** [alexguirre/RAGENativeUI#169]
When trying to open a dialogue box to edit integers, RageNativeUI will throw a memory error and lock up the game. Seems to be happening with the most recent build for RagePluginHook, RageNativeUI, and GTA:V
[RagePluginHook.log](https://github.com/user-attachments/files/18117851/RagePluginHook.log)

**Comment by alexguirre** [comment]
Did you download the latest release from today at https://github.com/alexguirre/RAGENativeUI/releases/tag/1.9.3 ?

People told me today that someone has been distributing an unofficial 1.9.3 version with their plugins for some time, that's actually old and will crash. Make sure you have installed the official version.

**Comment by Walkf** [comment]
Yes, I followed the link through the RPH Discord to your repo (here). I updated, then reinstalled, the most recent version.

**Comment by alexguirre** [comment]
LiveLights embeds the previous version of RNUI in its .dll and doesn't use the new version you installed, that's why it is still crashing. Wait for an update to LiveLights.
