### ISSUE TITLE
Display issue on large resolution setups

### ISSUE THREAD

**Issue by m7media** [alexguirre/RAGENativeUI#19]
Please see attached images. My display is 5890x1080. This happens with all plugins using RAGENativeUI.
![2016-08-21 10_30_04-greenshot](https://cloud.githubusercontent.com/assets/9528968/18150162/9c7a237a-6f99-11e6-8500-01479cfd38d0.jpg)
![2016-08-21 10_30_46-greenshot](https://cloud.githubusercontent.com/assets/9528968/18150163/9c7feab2-6f99-11e6-8493-c3ab90ce0a52.jpg)
![2016-08-21 10_31_41-greenshot](https://cloud.githubusercontent.com/assets/9528968/18150164/9c87578e-6f99-11e6-8907-93833f4cb282.jpg)

**Comment by m7media** [comment]
Anyone there? I know I'm one of the few people who run a display setup like this, but any help towards solving this issue would be greatly appreciated!

**Comment by gabgab145** [comment]
Nope i got the exact same problem on 5240x1050

**Comment by gabgab145** [comment]
Nope i got the exact same problem on 5240x1050

**Comment by zinc1282** [comment]
Ditto on this issue.  Since most plugins are using this UI now, it make me choose between playing on three screens or playing with readable menus.  Very frustrating.

**Comment by alexguirre** [comment]
@m7media @gabgab145 @zinc1282  Can any of you execute this command in the RPH console and tell what values does it show?
```
Execute "Game.LogTrivial(""WIDTH:""+Game.Resolution.Width.ToString());Game.LogTrivial(""HEIGHT:""+Game.Resolution.Height.ToString());"
```
Just copy and paste in the console.

**Comment by gabgab145** [comment]
it said generated Code 438852109: WIDTH:5260 and generated Code 438852109: HEIGHT:1050

**Comment by alexguirre** [comment]
@gabgab145 Thanks, at first I thought the issue was that RPH gave the wrong resolution values but it seems to be working fine.
Now I'm pretty sure I've identified where the issue is and I'm trying to find the fix.

**Comment by gabgab145** [comment]
@alexguirre let me know how it go thanks for the great work !

**Comment by Mamba130** [comment]
Same problem at 3840 x 1080 px.

**Comment by martcink7** [comment]
@alexguirre Thank you for all the hard work on this. Was wondering if you were able to point me in the right direction to a fix for the issue described in this thread? I am at 3840 x 1080 px screen resolution and am having the same issue with the UI menu distorted for certain mods. Any help would be greatly appreciated. Thank you.

**Comment by ziipzaaapM16A4** [comment]
same here 5760*1920
at least something hardcoded i can use for now?

**Comment by alexguirre** [comment]
Can anyone try this build? It may not be compatible will all plugins yet, but it should look more or less right in these resolutions.

[RAGENativeUI.zip](https://github.com/alexguirre/RAGENativeUI/files/4400143/RAGENativeUI.zip)

**Comment by ziipzaaapM16A4** [comment]
Works for me BUT hard to test when almost every plugin deactivates themself because the version is to old.

**Comment by alexguirre** [comment]
@ziipzaaapM16A4 Ah, yeah, sorry about that, this build has the same version as the latest release.
[RAGENativeUI.zip](https://github.com/alexguirre/RAGENativeUI/files/4401604/RAGENativeUI.zip)

Also, does mouse selection work correctly? Like the highlighted option matches the option pointed by the mouse and the same for clicking. I don't think it does yet.
Since plugins may disable mouse selection, you can use this example plugin to test the mouse: place it Plugins, load it and press F5 to open the menu. 
[MenuExampleProject.zip](https://github.com/alexguirre/RAGENativeUI/files/4401634/MenuExampleProject.zip)

**Comment by ziipzaaapM16A4** [comment]
Mouse selection: No
mouse over does highlight: No
highlight position is where mouse is: not able to test since there is no highlight

Tested with
RAGENativeUI Showcase: resolution is good. mouse is activated. Mouse selection does not work
Ultimate Backup: resolution is good. mouse not activated
EUPmenu: resolution is good. mouse not activated
Vehicle Search Plugin: Progressbar is still to short. probably the TimerBarPool and BarTimerBar are not set up for this resolution.

**Comment by alexguirre** [comment]
@ziipzaaapM16A4 Thanks. And yeah, timer bars aren't fixed yet.

**Comment by ziipzaaapM16A4** [comment]
@alexguirre no problem ^^. 
nice. i guess i can keep that version for now?

**Comment by alexguirre** [comment]
@ziipzaaapM16A4 Sure

**Comment by alexguirre** [comment]
@ziipzaaapM16A4 Can you check how timer bars look in this build? 
[RAGENativeUI.zip](https://github.com/alexguirre/RAGENativeUI/files/4427023/RAGENativeUI.zip)

**Comment by ziipzaaapM16A4** [comment]
looks great.
timer bars have now at 5760*1920 the size just like normal 1920*1080 resolution.
![resolution prove](https://user-images.githubusercontent.com/61912095/78362776-f4398a80-75ba-11ea-8418-dc63d2710c4d.jpg)

Thank you so much.

**Comment by alexguirre** [comment]
@ziipzaaapM16A4 Yeah, not showing the mouse was intended. I removed mouse controls from that build.
Anyways, I reimplemented mouse controls in this build, can you check if they work correctly? 
[RAGENativeUI.zip](https://github.com/alexguirre/RAGENativeUI/files/4433036/RAGENativeUI.zip)

And, btw, how do the pause menus from RNUI look? I'm guessing they are broken as well. If you don't have any plugin that uses pause menus, try this example plugin, load it and press F5 to open it: 
[PauseMenuExampleProject.zip](https://github.com/alexguirre/RAGENativeUI/files/4433038/PauseMenuExampleProject.zip)

**Comment by ziipzaaapM16A4** [comment]
@alexguirre 
i used both plugins. mouse still not working and found some other bugs.
https://youtu.be/q4h3rWj7kUA  (PauseMenu)
https://youtu.be/xMs1zjrRfNE   (Showcase UI)
pm me if you wanna quick fix something. i will be ready

**Comment by alexguirre** [comment]
@ziipzaaapM16A4 Ok, try this one. It draws rectangles where the mouse checks are done: 
[RAGENativeUI.zip](https://github.com/alexguirre/RAGENativeUI/files/4443590/RAGENativeUI.zip)
This is how it looks for me:
![rnui](https://user-images.githubusercontent.com/12873137/78659403-c9f21080-78cb-11ea-8e8a-4f32b37a8546.png)

As for the pause menu, not going to be fixing it for now, it will just delay the menu and timer bars fixes.

**Comment by ziipzaaapM16A4** [comment]
ok ok i got some more informations.
mouse works but its everything orientated to the right.
video comes in a few minutes

**Comment by ziipzaaapM16A4** [comment]
New Report
https://youtu.be/0WNoZyBfBLU

**Comment by alexguirre** [comment]
@ziipzaaapM16A4 Ugh, that is really weird. I'm pretty much doing the same as the game scripts do with their menus.
Can you try running this command in the RPH console? With the menu open, in each of yours screens place the mouse around its center and check which value it shows.
```
get "NativeFunction.Natives.GetDisabledControlNormal<float>(2, 239)"
```

**Comment by ziipzaaapM16A4** [comment]
@alexguirre do you have discord or ts? it much easier when i just show you the bug instead of uploading a new video?

**Comment by alexguirre** [comment]
@ziipzaaapM16A4 Yeah, I have discord: alexguirre#0721

**Comment by alexguirre** [comment]
For anyone having this issue, you can use this build until the next version is released.
[RAGENativeUI.zip](https://github.com/alexguirre/RAGENativeUI/files/4465099/RAGENativeUI.zip)

**Comment by Sebboo** [comment]
I had someone on the RPH server try that build, and he had the following issue that you can see on the screenshot. 
![image](https://user-images.githubusercontent.com/35180563/79165683-e61e1200-7de3-11ea-8c8e-68f3a9ce88fd.png)
You can DM me on Discord or so and I can get you in touch with him if needed. He doesn't have a GitHub account.

**Comment by ziipzaaapM16A4** [comment]
> I had someone on the RPH server try that build, and he had the following issue that you can see on the screenshot.
> ![image](https://user-images.githubusercontent.com/35180563/79165683-e61e1200-7de3-11ea-8c8e-68f3a9ce88fd.png)
> You can DM me on Discord or so and I can get you in touch with him if needed. He doesn't have a GitHub account.


This is not a bug. This is the very new disappointing update of Bejoijo's Plugins.
He is using now a oversized pic.

**Comment by alexguirre** [comment]
> 
> 
> > I had someone on the RPH server try that build, and he had the following issue that you can see on the screenshot.
> > ![image](https://user-images.githubusercontent.com/35180563/79165683-e61e1200-7de3-11ea-8c8e-68f3a9ce88fd.png)
> > You can DM me on Discord or so and I can get you in touch with him if needed. He doesn't have a GitHub account.
> 
> This is not a bug. This is the very new disappointing update of Bejoijo's Plugins.
> He is using now a oversized pic.

Actually, seems to be caused by a change in behaviour in RAGENativeUI added when fixing the display issues. Now, it uses the resolution of the image to determine the size of the banner, which looks correct on images with an aspect ratio similar to the default image. But the image used is a square with resolution 256x256 so it calculates the wrong size.
I will change it to always used the default image resolution, so it looks correct no matter which image a dev puts there. It should fix this issue.

**Comment by ziipzaaapM16A4** [comment]
Holdup, what?
But the bug just occured when i updated Bejoijo's Plugins. So how is this possible.

**Comment by alexguirre** [comment]
> 
> 
> Holdup, what?
> But the bug just occured when i updated Bejoijo's Plugins. So how is this possible.

I guess he was using a banner-like image (resolution 512x128) before but now using that square image (resolution 256x256).
This display size is calculated by RAGENativeUI, a dev can't change its height.

**Comment by alexguirre** [comment]
It works on correctly on the released version 1.6.3 because it has a fixed banner size independent of the image resolution. Now, it calculates its size based on its resolution, which I will change to calculate based on the default banner resolution, so it looks like in 1.6.3.

**Comment by alexguirre** [comment]
This build should fix the banner issue: 
[RAGENativeUI.zip](https://github.com/alexguirre/RAGENativeUI/files/4475337/RAGENativeUI.zip)

**Comment by FSXLiveriesdotcom** [comment]
Hi @alexguirre 
The file from post above fixed most of  the issues for me with overlapped in couple of plugins, except one - CompuLite. 
As you can see on the screenshot below, text is bit messed, even though I have safe zone set on max. 
Display is 3840x1080p.
Screenshot: https://imgur.com/NdVlS3i

**Comment by pnwparksfan** [comment]
@FSXLiveriesdotcom CompuLite does a bunch of custom stuff which overwrites default RNUI behavior. The author of CompuLite has refused to contribute back any of that custom functionality to the open source RNUI project, so fixing it would likely require the author to update their own code.

**Comment by FSXLiveriesdotcom** [comment]
Thank you, @pnwparksfan. I will contact author of CompuLite then.

**Comment by alexguirre** [comment]
@FSXLiveriesdotcom Regardless of CompuLite, pause menus have not been fixed. The vanilla pause menus are not handled in scripts, so I can't copy some of the positioning/sizing code, and I don't have a setup with those resolutions, so I have to depend on other people to test it and makes development really slow.

May fix it in the future, but it isn't something I'm working on right now.

**Comment by FSXLiveriesdotcom** [comment]
Thanks for answer, Alex. 
If you decide to work on it and you will need a testers, just let me know here. I will try to provide some feedback.
