### ISSUE TITLE
SetKey() overload method not working

### ISSUE THREAD

**Issue by alexguirre** [alexguirre/RAGENativeUI#2]
The **SetKey(Common.MenuControls control, Keys keyToSet)** overload isn't working. It might be related to the HasControlJustBeenPressed(), HasControlJustBeenReleased() and IsControlBeingPressed() methods.

The other overload methods (SetKey(Common.MenuControls control, GameControl gtaControl) and SetKey(Common.MenuControls control, GameControl gtaControl, int index)) work.

Basically the menu doesn't work with **Keys** enum.

**Comment by Guad** [comment]
That needs a rewrite since it was supposed to work with ScriptHookVDotNet's OnKeyDown event.

**Comment by alexguirre** [comment]
Check this pull request #4

**Comment by alexguirre** [comment]
Fixed in v1.3
