### ISSUE TITLE
Zip download of 1.6 broken

### ISSUE THREAD

**Issue by agkelly4** [alexguirre/RAGENativeUI#23]
Hi! Your download link for RageNativeUI.zip, v. 1.6, downloads an empty file to my network. It seems to be a broken asset because we can download 1.5.1 correctly.

**Comment by Ezzie15** [comment]
Same problem  here

**Comment by alexguirre** [comment]
It's working fine for me

**Comment by waski35** [comment]
Its also working on my end (I downloaded it a few days ago)

**Comment by Ezzie15** [comment]
i tried opening with winrar and that worked so i dont know what the problem was but this works for me

**Comment by P1975** [comment]
Yes, use winrar to open the file. winzip shows up as an empty file. thanks ezzie15 ;)
