### ISSUE TITLE
zip file not valid

### ISSUE THREAD

**Issue by justandy918** [alexguirre/RAGENativeUI#26]
the zip file will not open. says invalid or empty zip.  Needing the RAGENativeUI.dll file

**Comment by alexguirre** [comment]
Tihs has already been discussed #23 , try using WinRar.

**Comment by justandy918** [comment]
I can't get my command bar to work using F4. By using Albo1125 LSPDFR Troubleshooter tool it says that I'm missing "RAGENativeUI.dll" and a link to download this file on your GitHub  How do I get a RAGENativUI.dll from your files? or is there another download? Any help would be much appreciated.  Trying to get this running for my kid as you can tell I'm in way over my head.

**Comment by alexguirre** [comment]
Again, you probably need to use WinRar to open the .zip.
Anyways, this is a direct download of the .dll file: https://drive.google.com/file/d/0B2-oLPylQP9rbkFMandfelN0QzQ/view?usp=sharing
