### ISSUE TITLE
 FPS drops on patch 1290/RPH 0.60

### ISSUE THREAD

**Issue by BejoIjo** [alexguirre/RAGENativeUI#29]
Using 1.6.2 on patch 1290/RPH 0.60

Unfortunately the FPS still drops when player is approaching the stopped driver.
The good thing is, when we press E to open traffic stop menu, the FPS is back up.
I have no idea. perhaps it's also related to traffic policer  which suppresses the original LSPDFR traffic stop menu plugin.

Opening EUP menu, the FPS is still dropping but better than before.

**Comment by alexguirre** [comment]
The FPS drops related to RAGENativeUI only occur when a menu is open. In my system(with just a testing menu) it went from dropping ~40FPS to ~2FPS in 1.6.2, so there was an improvement. 

This performance issue can be caused by other plugins too, not only RNUI was affected.

**Comment by BejoIjo** [comment]
I can understand that. I'm just curious why it didn't happen on 1180 & RPH 0.57?
Perhaps RPH 0.60 and traffic policer plugin are also involved on the issue i mentioned above.
Rockstar is the main culprit. They don't like modding community.

**Comment by alexguirre** [comment]
I suspect it's due to the obfuscation that R* added to the native functions registration table in v1290, I can't say for sure as I don't know RPH's internal implementation.
