### ISSUE TITLE
AppDomain-global bool for if a menu is open

### ISSUE THREAD

**Issue by LSPDFR-PeterU** [alexguirre/RAGENativeUI#41]
It would be useful if LSPDFR plugins (running in the same AppDomain) could know if another plugin is rendering a menu, to avoid mulitple menus being visible at once. Is it possible, even across pools, to have a bool to indicate if any `Menu.IsVisible`?

**Comment by alexguirre** [comment]
For version 2.0, there exists the static property `Menu.IsAnyMenuVisible` which works across AppDomains, so any RPH plugin can know if any other RPH plugin has opened a menu.

**Comment by LSPDFR-PeterU** [comment]
I guess I didn't look at the right branch for this existing feature, sorry!
