### ISSUE TITLE
No mouse cursor on PauseMenu

### ISSUE THREAD

**Issue by BejoIjo** [alexguirre/RAGENativeUI#44]
I saw in the TabView.cs code that you commented the lines to display and support mouse cursor.
Why did you do it?

The PauseMenu is a really good infrastructure to build a police computer for LSPDFR which is I'm now trying to do.

**Comment by alexguirre** [comment]
The mouse controls weren't working correctly, I don't remember the specific issues with it though.

**Comment by BejoIjo** [comment]
ah i see... btw. thanks for all your open source codes.
your works inspire me a lot on making LSPDFR plugins :)
