### ISSUE TITLE
Window size

### ISSUE THREAD

**Issue by ainesophaur** [alexguirre/RAGENativeUI#5]
Can you implement a way to provide a configuration file for setting the Container size? I have a three monitor setup and I can barely see any options. Alternatively you can calculate the size based on the current window size and then keep the ratio you want (What I assume LSPDFR is doing)

https://github.com/alexguirre/RAGENativeUI/blob/9fc280047e630cfaee354b89c3441f95fe43440c/Source/UIMenu.cs#L180

![menu_issue](https://cloud.githubusercontent.com/assets/4686198/12857284/42db790c-cc17-11e5-9ad4-3f4124dc1b04.PNG)

**Comment by ainesophaur** [comment]
On a side note, if you welcome PRs then I'm more than willing to assist with providing the functionality that Im requesting.

**Comment by alexguirre** [comment]
Feel free to open a pull request, calculating the size would be the ideal solution.

**Comment by ainesophaur** [comment]
I found this isn't an issue on versions 1.3 and higher. Unfortunately some of the plugins I depend on still have a requirement on 1.2 which I will ask them to update. Thanks again for responding and for your great work.
