### ISSUE TITLE
While list item is disabled, it can still be modified

### ISSUE THREAD

**Issue by JoeTheHuman** [alexguirre/RAGENativeUI#7]
I had a disabled list item for one of my plugins, however, it could still be changed. I had it disabled to prevent crashes when a player wasn't in a vehicle.

**Comment by alexguirre** [comment]
Do you mean that you can still move the items in the list left/right?
I will investigate this and most likely will be fixed in the next version.

**Comment by JoeTheHuman** [comment]
Yep, Exactly

On Friday, June 10, 2016, alexguirre <notifications@github.com> wrote:

> Do you mean that you can still move the items in the list left/right?
> I will investigate this and most likely will be fixed in the next version.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/alexguirre/RAGENativeUI/issues/7#issuecomment-225230928>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKgjKFa5Er8CkH9MEo7eiXs9RDyWa2pPks5qKZEcgaJpZM4Iy50z>
> .
>


-- 
Thanks,
Joe
