### ISSUE TITLE
Broken UI when using high resolution

### ISSUE THREAD

**Issue by Mahnut** [alexguirre/RAGENativeUI#75]
When using 7780 x 1440 resolution(triple monitors), all plugins that use RAGENativeUI, their interface is broken . Could you please fix it , i beg.

**Comment by alexguirre** [comment]
Try the RAGENativeUI.dll here: https://github.com/alexguirre/RAGENativeUI/issues/19#issuecomment-613428424
Should fix the menus (except the ones that look the pause menu) and timer bars.

**Comment by Mahnut** [comment]
works perfectly, Thank you . God bless.
