### ISSUE TITLE
Support for skipping items

### ISSUE THREAD

**Issue by alexguirre** [alexguirre/RAGENativeUI#85]

**Comment by oliverpope03** [comment]
Could i take a crack at doing this if you havent already started anything (my plugins next update is done just waiting for the new RNUI version, so im bored xD)

**Comment by alexguirre** [comment]
Sure, I haven't started working on this yet. I'm planning on releasing 1.7 once RPH supports tomorrow's DLC update so probably this won't be part of 1.7, but could be added in a minor version at a later date.

**Comment by oliverpope03** [comment]
No worries, oh yeah my plugins also waiting for that slipped my mind completely
