### ISSUE TITLE
ERROR: assemblyPath

### ISSUE THREAD

**Issue by TheDazzledLynx** [alexguirre/RAGENativeUI#9]
Hey.

I'm not able to load the plugin. 

ERROR: Could not load plugin from "C:\........\Plugins\RAGENativeUI.dll" Assembly RAGENativeUI.dll (RAGENativeUI, Version=1.4.1.0, Culture=neutral, PublicKeyToken=null) does not have the required Plugin attribute. Paramaternavn: assemblyPath

I'm trying to load it in RAGE Plugin Hook - Open Alpha - 0.39.946.8098 - a fresh install, with no other plugins installed prior to this.

I need this plugin to get RAGE_Transportation to work.

Am I doing something wrong?

This plugin doesn't show up in RPH Plugins Options either. But the other plugin I'm trying to get to work is showing.

**Comment by alexguirre** [comment]
RAGENativeUI isn't a RPH plugin, it can't be loaded. You only have to put the RAGENativeUI.dll in the GTA V root directory.

**Comment by TheDazzledLynx** [comment]
Ooohhh. I see. And it's working now. :)

Thanks for the answer.

May I suggest a short ReadMe to follow along with the ZIP, so idiots like me are in safe hands? ;)
