### ISSUE TITLE
Menus stretched in ultra widescreen setups since 1.7.0

### ISSUE THREAD

**Issue by waynieoaks** [alexguirre/RAGENativeUI#98]
Hi

I have noticed in 1.7.0 that the menus are larger than that of 1.6.3 when using an ultra widescreen 21:9 setup at 3440x1440. 
This is a particular problem with the full screen menus (e.g. used in compulite or Computer+) as it stretches off the screen completely and the mouse pointer appears to click in the wrong location. 

![fullscreen_1 6 3](https://user-images.githubusercontent.com/5962977/91701972-facf2c80-eb6f-11ea-8156-4fff2a8c8c13.png)
![fullscreen_1 7 0](https://user-images.githubusercontent.com/5962977/91701976-fc005980-eb6f-11ea-865c-58a2e295542d.png)
![menu_1 6 3](https://user-images.githubusercontent.com/5962977/91701980-fc98f000-eb6f-11ea-986d-406ea566fe8c.png)
![menu_1 7 0](https://user-images.githubusercontent.com/5962977/91701985-fd318680-eb6f-11ea-991f-417ba2e3a7a6.png)

**Comment by alexguirre** [comment]
@waynieoaks You can try this build until next version gets released. This is not a full fix, it only fixes the full screen menu but that seems to be biggest issue.
[RAGENativeUI.zip](https://github.com/alexguirre/RAGENativeUI/files/5314107/RAGENativeUI.zip)
As for the mouse pointer, mouse controls are not yet implemented in RAGENativeUI for full screen menus, it is something that CompuLite implements so not sure if they will work correctly with this build.
The normal menus are still stretched.

**Comment by waynieoaks** [comment]
Hi

Thank you for the temporary fix, it has stopped the stretched issue on the screen, but as you explained the mouse still does not line up, which is likely the plugin implementation. If you do need any help testing I am able to help up to the 3440x1440 resolution, (and in any other way if I can). 

Many thanks.
